### PR TITLE
Integration

### PR DESCRIPTION
**Pull request by spheromak**
Putting this up here In case opscode might be interested. This is my cleanup and decouple of the rcb-ops fork of the opscode keepalived cookbook which brings in some nice LWRP's for managing keepalived. I removed the rcb-ops specific bits and made it a more generic "library" cookbook as well as adding some integration tests. If this is rejected/closed I am fine with that, but I do think it would be good to get this back into the canonical source.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.getchef.com/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @rcbjenkins
* @breu
* @jcannava

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by breu** [comment]
thanks for resurrecting a zombie PR Curry bot.

**Comment by tas50** [comment]
Going forward we're going to do what we can to make sure we don't end up with 2 year old PRs.

**Comment by tas50** [comment]
Since the CLA hasn't been signed in over 6 month for this PR I'm going to close it out at this point.  If the author would like to sign the CLA feel free to open up the PR again.

**Comment by spheromak** [comment]
I have a CLA it is signed, but there are multiple authors. Most the work
was doing by rackspace, and I integrated it to work with upstream.  No idea
how you resolve that.

**Comment by breu** [comment]
I'm also pretty certain that other than the jenkins servers I had a CLA signed when I was at Rackspace and so did @jcannava when the PR was first created.

**Pull request closed without merging**
