### PR TITLE
adds lvs_sync_daemon_interface configuration to the default template.

### PR DESCRIPTION
**Pull request by schnika**
The lvs_sync_daemon_iterface is missing from the default configuration file.
It is documented here http://www.keepalived.org/pdf/UserGuide.pdf.

### CODE REVIEW

**Comment by chef-supermarket** [comment]
Hi. I am an automated pull request bot named Curry. There are commits in this pull request whose authors are not yet authorized to contribute to Chef Software, Inc. projects or are using a non-GitHub verified email address. To become authorized to contribute, you will need to sign the Contributor License Agreement (CLA) as an individual or on behalf of your company. [You can read more on Chef's blog.](https://www.chef.io/blog/2014/06/23/changes-to-the-contributor-license-agreement-process)

## GitHub Users Who Are Not Authorized To Contribute

The following GitHub users do not appear to have signed a CLA:

* @schnika

[Please sign the CLA here.](https://supermarket.chef.io/become-a-contributor)

**Comment by chef-supermarket** [comment]
Hi. Your friendly Curry bot here. Just letting you know that all commit authors have become authorized to contribute. I have added the "Signed CLA" label to this issue so it can easily be found in the future.

**Comment by tas50** [comment]
If you want to document this in the readme I'll get it merged in

**Comment by schnika** [comment]
@tas50. Sorry for the late response. It is documented in the Readme.md now. Tell me if I need anything else to do. Thanks and have a good day.

**Comment by nathwill** [comment]
@schnika this keyword is now supported in the pending release of this cookbook; closing this PR, but expect to see v2 ship soon!

**Comment by schnika** [comment]
@nathwill thanks for the info! good luck with the v2 release :)

**Pull request closed without merging**
